import { Saira, Geist_Mono } from "next/font/google";
import "./globals.css";

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
  weight: ["400", "700"],  // اختياري: أوزان الخط
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FurniShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${saira.variable} ${geistMono.variable} antialiased font-saira`}
      >
        {children}
      </body>
    </html>
  );
}
